package com.ilp3.system.entity;

import java.io.Serializable;
import java.util.Date;

public class Achievements implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievements.achievements_id
     *
     * @mbg.generated
     */
    private Integer achievementsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievements.supplier_id
     *
     * @mbg.generated
     */
    private Integer supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievements.achievements_name
     *
     * @mbg.generated
     */
    private String achievementsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievements.weight
     *
     * @mbg.generated
     */
    private Double weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievements.user_id_create
     *
     * @mbg.generated
     */
    private Integer userIdCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievements.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievements.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievements.totalcount
     *
     * @mbg.generated
     */
    private Integer totalcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievements.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievements.achieve_type
     *
     * @mbg.generated
     */
    private Integer achieveType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table achievements
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievements.achievements_id
     *
     * @return the value of achievements.achievements_id
     *
     * @mbg.generated
     */
    public Integer getAchievementsId() {
        return achievementsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievements.achievements_id
     *
     * @param achievementsId the value for achievements.achievements_id
     *
     * @mbg.generated
     */
    public void setAchievementsId(Integer achievementsId) {
        this.achievementsId = achievementsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievements.supplier_id
     *
     * @return the value of achievements.supplier_id
     *
     * @mbg.generated
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievements.supplier_id
     *
     * @param supplierId the value for achievements.supplier_id
     *
     * @mbg.generated
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievements.achievements_name
     *
     * @return the value of achievements.achievements_name
     *
     * @mbg.generated
     */
    public String getAchievementsName() {
        return achievementsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievements.achievements_name
     *
     * @param achievementsName the value for achievements.achievements_name
     *
     * @mbg.generated
     */
    public void setAchievementsName(String achievementsName) {
        this.achievementsName = achievementsName == null ? null : achievementsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievements.weight
     *
     * @return the value of achievements.weight
     *
     * @mbg.generated
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievements.weight
     *
     * @param weight the value for achievements.weight
     *
     * @mbg.generated
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievements.user_id_create
     *
     * @return the value of achievements.user_id_create
     *
     * @mbg.generated
     */
    public Integer getUserIdCreate() {
        return userIdCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievements.user_id_create
     *
     * @param userIdCreate the value for achievements.user_id_create
     *
     * @mbg.generated
     */
    public void setUserIdCreate(Integer userIdCreate) {
        this.userIdCreate = userIdCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievements.gmt_create
     *
     * @return the value of achievements.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievements.gmt_create
     *
     * @param gmtCreate the value for achievements.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievements.gmt_modified
     *
     * @return the value of achievements.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievements.gmt_modified
     *
     * @param gmtModified the value for achievements.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievements.totalcount
     *
     * @return the value of achievements.totalcount
     *
     * @mbg.generated
     */
    public Integer getTotalcount() {
        return totalcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievements.totalcount
     *
     * @param totalcount the value for achievements.totalcount
     *
     * @mbg.generated
     */
    public void setTotalcount(Integer totalcount) {
        this.totalcount = totalcount;
    }

    public Integer getScore() {
        return score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievements.score
     *
     * @return the value of achievements.score
     *
     * @mbg.generated


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievements.achieve_type
     *
     * @return the value of achievements.achieve_type
     *
     * @mbg.generated
     */
    public Integer getAchieveType() {
        return achieveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievements.achieve_type
     *
     * @param achieveType the value for achievements.achieve_type
     *
     * @mbg.generated
     */
    public void setAchieveType(Integer achieveType) {
        this.achieveType = achieveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievements
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Achievements other = (Achievements) that;
        return (this.getAchievementsId() == null ? other.getAchievementsId() == null : this.getAchievementsId().equals(other.getAchievementsId()))
            && (this.getSupplierId() == null ? other.getSupplierId() == null : this.getSupplierId().equals(other.getSupplierId()))
            && (this.getAchievementsName() == null ? other.getAchievementsName() == null : this.getAchievementsName().equals(other.getAchievementsName()))
            && (this.getWeight() == null ? other.getWeight() == null : this.getWeight().equals(other.getWeight()))
            && (this.getUserIdCreate() == null ? other.getUserIdCreate() == null : this.getUserIdCreate().equals(other.getUserIdCreate()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModified() == null ? other.getGmtModified() == null : this.getGmtModified().equals(other.getGmtModified()))
            && (this.getTotalcount() == null ? other.getTotalcount() == null : this.getTotalcount().equals(other.getTotalcount()))
            && (this.getScore() == null ? other.getScore() == null : this.getScore().equals(other.getScore()))
            && (this.getAchieveType() == null ? other.getAchieveType() == null : this.getAchieveType().equals(other.getAchieveType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievements
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAchievementsId() == null) ? 0 : getAchievementsId().hashCode());
        result = prime * result + ((getSupplierId() == null) ? 0 : getSupplierId().hashCode());
        result = prime * result + ((getAchievementsName() == null) ? 0 : getAchievementsName().hashCode());
        result = prime * result + ((getWeight() == null) ? 0 : getWeight().hashCode());
        result = prime * result + ((getUserIdCreate() == null) ? 0 : getUserIdCreate().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModified() == null) ? 0 : getGmtModified().hashCode());
        result = prime * result + ((getTotalcount() == null) ? 0 : getTotalcount().hashCode());
        result = prime * result + ((getScore() == null) ? 0 : getScore().hashCode());
        result = prime * result + ((getAchieveType() == null) ? 0 : getAchieveType().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievements
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", achievementsId=").append(achievementsId);
        sb.append(", supplierId=").append(supplierId);
        sb.append(", achievementsName=").append(achievementsName);
        sb.append(", weight=").append(weight);
        sb.append(", userIdCreate=").append(userIdCreate);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", totalcount=").append(totalcount);
        sb.append(", score=").append(score);
        sb.append(", achieveType=").append(achieveType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;

    }
}