package com.ilp3.system.dao;

import com.ilp3.system.entity.Achievements;
import com.ilp3.system.entity.AchievementsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AchievementsMapper {
     int insertinit(Achievements achievement);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievements
     *
     * @mbg.generated
     */
    long countByExample(AchievementsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievements
     *
     * @mbg.generated
     */
    int deleteByExample(AchievementsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievements
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer achievementsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievements
     *
     * @mbg.generated
     */
    int insert(Achievements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievements
     *
     * @mbg.generated
     */
    int insertSelective(Achievements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievements
     *
     * @mbg.generated
     */
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievements
     *
     * @mbg.generated
     */
    Achievements selectByPrimaryKey(Integer achievementsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievements
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Achievements record, @Param("example") AchievementsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievements
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Achievements record, @Param("example") AchievementsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievements
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Achievements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievements
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Achievements record);

    List<Achievements> selectBySupplierid(int supplierid);

    int insertBySupplierId(Achievements achievement);

    int countById(Integer supplierId);

    double selectByname(int aid);
}