package com.ilp3.system.dao;

import com.ilp3.system.entity.AchievementDetail;
import com.ilp3.system.entity.AchievementDetailExample;
import com.ilp3.system.entity.AchievementsDetail;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AchievementDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement_detail
     *
     * @mbg.generated
     */
    long countByExample(AchievementDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement_detail
     *
     * @mbg.generated
     */
    int deleteByExample(AchievementDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer achievementsDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement_detail
     *
     * @mbg.generated
     */
    int insert(AchievementDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement_detail
     *
     * @mbg.generated
     */
    int insertSelective(AchievementDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement_detail
     *
     * @mbg.generated
     */
    List<AchievementDetail> selectByExample(AchievementDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement_detail
     *
     * @mbg.generated
     */
    AchievementDetail selectByPrimaryKey(Integer achievementsDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AchievementDetail record, @Param("example") AchievementDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AchievementDetail record, @Param("example") AchievementDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AchievementDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievement_detail
     *
     * @mbg.generated
     * @param record
     */
    int updateByPrimaryKey(AchievementsDetail record);

}